<?php    

Class autobio_red {  	 public static function init() { 		 global $wp_version; 		 
// autobio requiere Wordpress 2.9 o superior 		 
if (version_compare($wp_version, "2.9", "<")) {  return false; 		 } 		 

self::addFilters(); 		 self::addActions(); 		 load_plugin_textdomain('autobio-div', false, dirname(plugin_basename(__FILE__ ))); 		 return true; 	 }  	  

public static function filterContactMethods($contactmethods) { 		 //add 		 $contactmethods['twitter'] = 'Twitter'; 		 $contactmethods['facebook'] = 'Facebook'; 		 $contactmethods['gplus'] = 'Google+';  $contactmethods['youtube'] = 'Youtube';	 // remove 		unset($contactmethods['yim']); 		 unset($contactmethods['aim']); 		 return $contactmethods; 	
}    	 

public static function filterContent($content = '') { 		 if( is_single() ) { 			 $autobio_showauttxt = get_option('autobio_showauttxt'); 			 $autobio_auttxt1 = get_option('autobio_auttxt1'); 			 $autobio_auttxt2 = get_option('autobio_auttxt2'); 			 $autobio_showautbio = get_option('autobio_showautbio'); 			 $autobio_showautintro = get_option('autobio_showautintro'); 			 $autobio_showautgra = get_option('autobio_showautgra'); 			 $author = array(); 			 $author['name'] = get_the_author(); 			 $author['twitter'] = get_the_author_meta('twitter'); 	 $author['facebook'] = get_the_author_meta('facebook'); 	 $author['gplus'] = get_the_author_meta('gplus');  $author['youtube'] = get_the_author_meta('youtube');			 $author['posts'] = (int)get_the_author_posts(); 			 ob_start(); 			 ?> 			 
<div id="autobio-div"> 				 <div class="autobio-div-info"> 				         <?php if($autobio_showautgra== 'y'){  ?> 					 <?php echo get_avatar( get_the_author_email(), '60' ); ?> 	 <?php } ?> 					 <h4><?php printf( esc_attr__( '%s %s'), $autobio_showautintro, get_the_author() ); ?></h4> 					 					 <?php if($autobio_showauttxt== 'y'){ ?> 					 <p class="autobio-div-text"><?php echo esc_attr(sprintf(__ngettext('%s %s %d %s', '%s %s %d %s', $author['posts'], $autobio_auttxt1, $autobio_auttxt2, 'autobio-div'), get_the_author_firstname().' '.get_the_author_lastname(), $autobio_auttxt1, $author['posts'], $autobio_auttxt2 )); ?>.</p> 					 <?php } else echo "<br />"; ?> 					 <?php if($autobio_showautbio== 'y'){ ?> 					 <p class="autobio-div-meta"> <?php echo get_the_author_meta('description'); ?></p> 					 <?php } else echo "<br />"; ?><ul> 						 <li class="first"><a rel="publisher" href="<?php echo get_author_posts_url( get_the_author_meta( 'ID' ) ); ?>"><img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/img/rss.png" width="32px" height="32px" /></a></li> 						 <li><a rel="author" href="<?php echo get_the_author_meta('url'); ?>" title="<?php echo esc_attr(sprintf(__('Ver la web de %s&#8217;s', 'autobio-div'), $author['name'])); ?>"><img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/img/Wordpress-icon.png" width="32px" height="32px" /></a></li> 						 <?php if(!empty($author['twitter'])): ?> 			 <li><a href="<?php echo $author['twitter']; ?>" title="<?php echo esc_attr(sprintf(__('Sigue a %s en Twitter', 'autobio-div'), $author['name'])); ?>" rel="external"><img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/img/Twitter-icon.png" width="32px" height="32px" /></a></li>
<?php endif; ?> 						 <?php if(!empty($author['facebook'])): ?> 						 <li><a href="<?php echo $author['facebook']; ?>" title="<?php echo esc_attr(sprintf(__('Hazte amigo de %s&#8217;s en Facebook', 'autobio-div'), $author['name'])); ?>" rel="external"><img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/img/Facebook-icon.png" width="32px" height="32px" /></a></li> <?php endif; ?>                          <?php if(!empty($author['gplus'])): ?>  <li><a href="<?php echo $author['gplus']; ?>" rel="me" title="<?php echo esc_attr(sprintf(__('A&ntilde;ade a %s en tu circulo', 'autobio-div'), $author['name'])); ?>" rel="external"><img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/img/Google-icon.png" width="32px" height="32px" /></a></li> 						 <?php endif; ?>	 <?php if(!empty($author['gplus'])): ?>  <li><a href="<?php echo $author['youtube']; ?>" rel="me" title="<?php echo esc_attr(sprintf(__('A&ntilde;ade a %s en tu circulo', 'autobio-div'), $author['name'])); ?>" rel="external"><img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/img/Youtube-icon.png" width="32px" height="32px" /></a></li> 						 <?php endif; ?>	 </ul>	 				 </div> 
<div class="comparte">Si te ha gustado este post, comp&aacute;rtelo!</div></div> 			 
<?php $autobio_loc = get_option('autobio_loc'); 				         $contend = $content; 				                                             if ($autobio_loc == 'bottom') $content = $content . ob_get_clean();                             		 if ($autobio_loc == 'top') $content = ob_get_clean() . $content;  }                   		 return $content; 	 }  	 
public static function pluginCss() { 		 if(file_exists(self::getPluginDir() . '/autobio-div.css')) { 			 wp_register_style('autobio-div', self::getPluginUrl().'/autobio-div.css'); 			 wp_enqueue_style('autobio-div'); 		  } 	}  	
 private static function getPluginDir() { 		 return WP_PLUGIN_DIR .'/'. dirname(plugin_basename(__FILE__)); 	 }  	
 private static function getPluginUrl() { 		  return WP_PLUGIN_URL .'/'. dirname(plugin_basename(__FILE__)); 	 }  	
 private static function addFilters() {                                     		 add_filter('user_contactmethods', array('autobio_red', 'filterContactMethods'));  		 add_filter('the_content', array('autobio_red', 'filterContent'));  	 }  	 
private static function addActions() { 		 add_action('wp_print_styles', array('autobio_red', 'pluginCss')); 	 }    }     
if(!autobio_red::init()) {  	echo 'autobio-div plugin requiere WordPress 2.9 o superior. Porfavor actualizate!';  }   ?>