<?php  	  
if($_POST['autobio_hidden'] == 'Y') { 		  //Form data sent 		  $autobio_loc = $_POST['autobio_loc']; 		  update_option('autobio_loc', $autobio_loc);  update_option('autobio_hidden', 1); 		  $autobio_auttxt1 = $_POST['autobio_auttxt1']; 		  update_option('autobio_auttxt1', $autobio_auttxt1); 		  $autobio_auttxt2 = $_POST['autobio_auttxt2']; 		  update_option('autobio_auttxt2', $autobio_auttxt2); 		  $autobio_showauttxt = $_POST['autobio_showauttxt']; 		  update_option('autobio_showauttxt', $autobio_showauttxt); 		  $autobio_showautbio = $_POST['autobio_showautbio']; 		  update_option('autobio_showautbio', $autobio_showautbio); 		  $autobio_showautintro = $_POST['autobio_showautintro']; 		  update_option('autobio_showautintro', $autobio_showautintro); 		  $autobio_showautgra = $_POST['autobio_showautgra']; 		  update_option('autobio_showautgra', $autobio_showautgra); 		  ?> 		  
<div class="updated"><p><strong><?php _e('Options saved.' ); ?></strong></p></div> 		  <?php 	} else { 		//Normal page display 		  $autobio_loc = get_option('autobio_loc'); 		  $autobio_auttxt1 = get_option('autobio_auttxt1'); 		  $autobio_auttxt2 = get_option('autobio_auttxt2'); 		  $autobio_showauttxt = get_option('autobio_showauttxt'); 		  $autobio_showautbio = get_option('autobio_showautbio'); 		  $autobio_showautintro = get_option('autobio_showautintro'); 		  $autobio_showautgra = get_option('autobio_showautgra'); 		 	} 	 	  
?>    <div class="wrap">   
<?php  echo "<h2>" . __( 'WPautobio', 'autobio_trdom' ) . "</h2>" . "version: 1.0 by <a href='http://www.laliamos.com' >SEO Valencia</a>"; ?>     <?php global $current_user;       get_currentuserinfo();        echo '<br /><br /><br />' . $current_user->user_firstname . ' Modo de posicici&oacute;n seleccionado:'; ?><strong><?php if($autobio_loc=='top') echo "Al comienzo del Post" ;   if($autobio_loc=='bottom') echo "Al final del Post" ;   if($autobio_loc=='manual') echo "Manualmente" ;   ?></strong>   
<form name="autobio_form" action="<?php echo str_replace( '%7E', '~', $_SERVER['REQUEST_URI']); ?>" method="POST"> 	  <input type="hidden" name="autobio_hidden" value="Y"> <br /><br /> <br />  <?php echo "Donde quieres mostrar WPautobio en tus posts:"; ?><br />   <input type="radio" name="autobio_loc" value="top"<?php if ($autobio_loc=='top') { echo ' checked="checked"'; } ?> /> Comienzo del Post<br />   <input type="radio" name="autobio_loc" value="bottom"<?php if ($autobio_loc=='bottom') { echo ' checked="checked"'; } ?> /> Final del Post<br />   <input type="radio" name="autobio_loc" value="manual"<?php if ($autobio_loc=='manual') { echo ' checked="checked"'; } ?> /> Manualmente<br /><br /> <br />  <?php echo "Quieres mostrar el gravatar del Author en WPautobio?"; ?><br />   <input type="radio" name="autobio_showautgra" value="y"<?php if ($autobio_showautgra=='y') { echo ' checked="checked"'; } ?> /> Si   <input type="radio" name="autobio_showautgra" value="n"<?php if ($autobio_showautgra=='n') { echo ' checked="checked"'; } ?> /> No<br />   <br />  <?php echo "Escribe lo que quieres que aparezca antes del nombre del autor(Escribe algo como Acerca de o Conoce a):"; ?><br />   <input type="text" name="autobio_showautintro" value="<?php echo $autobio_showautintro ; ?>"/> (el nombre del autor se mostrar&aacute; autom&aacute;ticamente) (El resultado ser&aacute;: Conoce a nombre del autor o Acerca de nombre del autor)<br />  <br />  <?php echo "Quieres mostrar el texto de la bio del autor en WPautobio?"; ?><br />   
<input type="radio" name="autobio_showautbio" value="y"<?php if ($autobio_showautbio=='y') { echo ' checked="checked"'; } ?>/> Si   <input type="radio" name="autobio_showautbio" value="n"<?php if ($autobio_showautbio=='n') { echo ' checked="checked"'; } ?> /> No<br />   <br />  <?php echo "Quieres mostrar el numero del post del autor?"; ?><br />   <input type="radio" name="autobio_showauttxt" value="y"<?php if ($autobio_showauttxt=='y') {   echo ' checked="checked"'; } ?> /> Si <input type="radio" name="autobio_showauttxt" value="n"<?php if ($autobio_showauttxt=='n') {   echo ' checked="checked"'; } ?> /> No<br />   <br />  
<?php echo "Escribe el texto a mostrar para el numero de posts:"; ?><br /> <input type="text" name="autobio_auttxt1" value="<?php echo $autobio_auttxt1 ; ?>"/> (Numero de posts)   <input type="text" name="autobio_auttxt2" value="<?php echo $autobio_auttxt2 ; ?>" /><br /> <p class="submit"> 	  <input type="submit" name="Submit" value="Actualizar Opciones" /> 	</p> </form>   
<?php if($autobio_loc=='manual'){  		  echo "Usa el shortcode [author_bio] donde quieras que aparezca tu WPautobio <textarea rows='1' cols='30'><?php autobio_manual(); ?>/textarea> en cualquier parte del c&oacute;digo fuente de tu theme actual. Puedes modificar el archivo single.php para colocar el shortcode."; 		  } 		  
echo"<br /><br /><br /><br /><br />"; ?>    <?php echo 'Ejemplo:<br />'; ?>   <img src="<?php echo get_site_url(); ?>/wp-content/plugins/WPautobio/demo.png" alt="demo" />   <?php echo '<br /><br /><br />Plugin Developer: <strong><a href="http://feeds.feedburner.com/laliamoscom">Marc C. G.</a></strong>. Hazte amigo en <a href="http://www.facebook.com/pages/WWWLALIAMOSCOM/127061537325752">Facebook</a>, <a href="https://plus.google.com/104303130170547990874">Google+</a> or in <a href="http://twitter.com/laliamos">Twitter</a>.'; ?>   
</div>